Milestone 4
okikiola11/react-calculator pull request #4
Opened 2021-05-20 14:00 UTC by okikiola11

- Created a new logic folder inside src and initialized (calculate.js and operate.js)

- Implemented the calculate.js module
-- it contains the calculate method
-- the calculate method accepts a calculator data object and a button name as arguments.
-- the calculator data object contains total, next and operation as properties
-- buttonName argument mutates the calculator’s data object

- Implemented the operate.js module
-- it implements the Operate method.
-- Operate function accepts numberOne, numberTwo and operation as arguments.
-- it performs a simple math operation.

- Added calculate.js to the App component
-- Imported the calculate function.

2021-05-20 15:56 UTC, trekab requested changes
#### Changes Required! :recycle: 
Well done @okikiola11! So far so good. There are a few changes for you to work on to complete this milestone. These include:

- [ ] As indicated in the code comments below, try to name the operate and calculate functions more appropriately to follow industry standards.
- [ ] Fix the issue where you used `Calculate` as a component in the `App` component. (Details highlighted in the code comment below)
- [ ] Fix the logic for the `%` operator as illustrated below.

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__[Treasure Kabareebe](https://trekab.github.io)__

2021-05-20 15:56 UTC, trekab commented on src/components/App.js
> +    <Calculate />
It appears that you used `Calculate` as a react component. It should be used as a function that other components will rely on to perform calculations. It is therefore better to remove the `<Calculate/>` line.
```suggestion
    <ButtonPanel />
```

2021-05-20 15:56 UTC, trekab commented on src/logic/calculate.js
> +
It is better to name your javascript functions starting with a lower case letter. Check out some highlighted JS coding conventions [here](https://www.w3schools.com/js/js_conventions.asp). __Note:__ This applies to the `operate` function as well.

2021-05-20 15:56 UTC, trekab commented on src/logic/operate.js
> +  }
The `%` modifier should  turn the number into a percentage based number, `e.g. 95 % == .95` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/performOperate.png))

2021-05-25 01:51 UTC, bellom approved these changes
## Hi @okikiola11  :clap: 

**Great work making all the necessary corrections from the previous review.**

**Do well to check my comment and make the little changes before merging.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-05-25 01:51 UTC, bellom commented on src/components/App.js
> -import Calculate from '../logic/calculate';
Oops, you're not supposed to remove this line, you will need it in the next milestone, kindly add it back before merging, I trust you can do this. 👀  on you!....

2021-05-25 07:27 UTC, bellom commented on src/components/App.js
> +import calculate from '../logic/calculate';
👍

2021-05-25 07:34 UTC, merged